runtime: python
env: flex
entrypoint: python application.py

runtime_config:
    python_version: 3

handlers:
- url: /Rail_Road/static
  static_dir: static
- url: /.*
  script: application.app

libraries:
- name: ssl
  version: latest
